spring:
  application:
    name: JavaTraining

  datasource:
    url: jdbc:postgresql://localhost:5432/javatraining
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liytKsZK32FpzXSQ
            client-secret: eca2384a102c0ad5778e1d7125d9dce7bf2fd533
            scope: read:user, user:email
      resourceserver:
        jwt:
          jwk-set-uri:

  messages:
    basename: messages
    encoding: UTF-8

logging:
  level:
    com.homeapp.javatraining: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: "dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEphdmFUcmFpbmluZyBhcHBsaWNhdGlvbiBmb3IgSldUIHRva2VuIGdlbmVyYXRpb24="
  expiration: 900000
  refresh-expiration: 2592000000